# .github/workflows/deploy.yml
name: Deploy to VPS

on:
  push:
    branches: [ main, master ]  # Canvia per la teva branca principal
  workflow_dispatch: # Permet executar manualment

env:
  REGISTRY: ghcr.io
  IMAGE_FRONTEND: ghcr.io/EricZapater/acorda-web
  IMAGE_BACKEND: ghcr.io/EricZapater/acorda-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: |
          ${{ env.IMAGE_FRONTEND }}:latest
          ${{ env.IMAGE_FRONTEND }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push Backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: |
          ${{ env.IMAGE_BACKEND }}:latest
          ${{ env.IMAGE_BACKEND }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /home/${{ secrets.VPS_USER }}/acorda
          
          # Login al registry
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Pull noves imatges
          docker pull ${{ env.IMAGE_FRONTEND }}:latest
          docker pull ${{ env.IMAGE_BACKEND }}:latest
          
          # Actualitzar docker-compose amb les noves imatges
          docker-compose down
          docker-compose up -d
          
          # Neteja imatges antigues
          docker image prune -f
          
          echo "✅ Desplegament completat!"

    - name: Verify deployment
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /home/${{ secrets.VPS_USER }}/acorda
          docker-compose ps
          echo "🌍 App disponible a: https://acorda.zenith.ovh"
